/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atelierswing.view;

import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author formation
 */
public class JPanelPrincipal extends javax.swing.JPanel {

    public void remplaceComposantCentral(JPanel nouveauPanneau){
        
        // Supprime panneau au centre si exite
        BorderLayout layout = (BorderLayout) this.getLayout();
        Component component = layout.getLayoutComponent( BorderLayout.CENTER );
        if( component!=null ){
            
            this.remove(component);
        }
        
        // Ajoute nouveauPanneau au centre
        this.add(nouveauPanneau, BorderLayout.CENTER);
        
        // Raffraichit l'affichage de l'objet actuel (un JPanelPrincipal donc) et
        // de tous ses composants enfants, petits enfants, ...
        this.validate();
    }
    
    /**
     * Creates new form JPanelPrincipal
     */
    public JPanelPrincipal() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        jbHotels = new javax.swing.JButton();
        jbChambres = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jToolBar2.setRollover(true);

        jbHotels.setText("Hotels");
        jbHotels.setFocusable(false);
        jbHotels.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbHotels.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbHotels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHotelsActionPerformed(evt);
            }
        });
        jToolBar2.add(jbHotels);

        jbChambres.setText("Chambres");
        jbChambres.setFocusable(false);
        jbChambres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbChambres.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jbChambres);

        add(jToolBar2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jbHotelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHotelsActionPerformed
        
        
        this.remplaceComposantCentral( new JPanelListeHotels2() );
    }//GEN-LAST:event_jbHotelsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton jbChambres;
    private javax.swing.JButton jbHotels;
    // End of variables declaration//GEN-END:variables
}
